image: docker:latest

services:
  - docker:dind

stages:
  - tests
  - build

python-tests:
  image: python:3.8-buster
  script:
    - pip3 install -r requirements.txt
    - pytest

build-docker:
  stage: build
  script:
    - echo "Using dockerhub user $CI_REGISTRY_USER"
    - echo "Build image with tag $CI_COMMIT_REF_NAME"
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin
    - export IMAGE_NAME=duduardo23/photo-organizer
    - docker build -t "$IMAGE_NAME:$CI_COMMIT_REF_NAME" -t "$IMAGE_NAME:latest" .
    - docker push "$IMAGE_NAME:$CI_COMMIT_REF_NAME"
    - docker push "$IMAGE_NAME:latest"
  only:
    - tags
    